sonar.projectKey=gerps2_fiap-store
sonar.organization=gerps2
sonar.projectName=fiap-store

sonar.sources=src/frontend/projects
sonar.tests=src/frontend/projects
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/environments/**

sonar.javascript.lcov.reportPaths=src/frontend/coverage/lcov.info
sonar.typescript.tsconfigPath=src/frontend/tsconfig.json
