sonar.projectKey=fiap-store-aula4
sonar.organization=fiap-postech
sonar.projectName=fiap-store — Aula 4 CI/CD

sonar.sources=src/frontend/src
sonar.tests=src/frontend/src
sonar.test.inclusions=src/frontend/src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/frontend/src/environments/**

sonar.javascript.lcov.reportPaths=src/frontend/coverage/lcov.info
sonar.typescript.tsconfigPath=src/frontend/tsconfig.json
