apiVersion: v1
kind: Secret
metadata:
  name: backend-keys
  namespace: fiap-store
type: Opaque
data:
  es256-private.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZzNzRk5GbjJ2UWw0b1NsdFMKOUdzc0dsdHR1Mm5wMDVJb0dQOThOcnVTZEU2aFJBTkNBQVNoUVhDQ3VFa2RZcXFUaUsvK1lreHNKNjZtems1UgpWUGxwUzUxQjgzL1liM2F1SjgxVXpnTWl2bDgrNFd0YUlsdCsydnA2S2NQdmdwejc3NzlLK2hJTQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  es256-public.pem: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFb1VGd2dyaEpIV0txazRpdi9tSk1iQ2V1cHM1TwpVVlQ1YVV1ZFFmTi8yRzkycmlmTlZNNERJcjVmUHVGcldpSmJmdHI2ZWluRDc0S2MrKysvU3ZvU0RBPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
