server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.[0-9a-f]\{8,\}\.(js|css|woff2?)$ {
        add_header Cache-Control "max-age=31536000, immutable";
    }

    location = /index.html {
        add_header Cache-Control "no-store";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
